-- MySQL Script generated by MySQL Workbench
-- Thu Mar 10 16:24:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema punored
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `punored` ;

-- -----------------------------------------------------
-- Schema punored
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `punored` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `punored` ;

-- -----------------------------------------------------
-- Table `punored`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`comentario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`comentario` (
  `come_id` INT NOT NULL AUTO_INCREMENT,
  `come_usua_id` INT NULL,
  `come_mensaje` VARCHAR(255) NULL,
  `come_fechareg` DATETIME NULL,
  PRIMARY KEY (`come_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`encuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`encuesta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`encuesta` (
  `encu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `encu_titulo` VARCHAR(150) NULL DEFAULT NULL,
  `encu_descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `encu_foto` VARCHAR(45) NULL DEFAULT NULL,
  `encu_usua_id` INT(11) NULL DEFAULT NULL,
  `encu_actual` BIT(1) NULL,
  PRIMARY KEY (`encu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`encuesta_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`encuesta_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`encuesta_detalle` (
  `deta_id` INT(11) NOT NULL AUTO_INCREMENT,
  `deta_encu_id` INT(11) NULL DEFAULT NULL,
  `deta_alternativa` VARCHAR(150) NULL DEFAULT NULL,
  `deta_puntos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`deta_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_encuesta_detalle_encuesta1_idx` ON `punored`.`encuesta_detalle` (`deta_encu_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`entrada` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`entrada` (
  `entr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `entr_tipo_id` INT NULL,
  `entr_usua_id` INT(11) NULL DEFAULT NULL,
  `entr_titulo` VARCHAR(150) NULL DEFAULT NULL,
  `entr_resumen` VARCHAR(255) NULL,
  `entr_contenido` TEXT NULL DEFAULT NULL,
  `entr_dire_logo` VARCHAR(45) NULL,
  `entr_foto` VARCHAR(45) NULL DEFAULT NULL,
  `entr_url` VARCHAR(150) NULL DEFAULT NULL,
  `entr_fechareg` DATETIME NULL DEFAULT NULL,
  `entr_fechapub` DATETIME NULL DEFAULT NULL,
  `entr_espublico` BIT(1) NOT NULL DEFAULT b'1',
  `entr_fechaven` DATETIME NULL,
  `entr_pmas` INT(11) NOT NULL DEFAULT '0',
  `entr_pmenos` INT(11) NOT NULL DEFAULT '0',
  `entr_cate_id` INT(11) NULL DEFAULT NULL,
  `entr_map_lat` VARCHAR(45) NULL,
  `entr_map_lng` VARCHAR(45) NULL,
  PRIMARY KEY USING BTREE (`entr_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE INDEX `fk_empleo_usuario1_idx` USING BTREE ON `punored`.`entrada` (`entr_usua_id`);

SHOW WARNINGS;
CREATE INDEX `fk_entrada_entrada_categoria1_idx` USING BTREE ON `punored`.`entrada` (`entr_cate_id`);

SHOW WARNINGS;
CREATE INDEX `fk_entrada_entrada_tipo1_idx` ON `punored`.`entrada` (`entr_tipo_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`entrada_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`entrada_categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`entrada_categoria` (
  `cate_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cate_tipo_id` INT NULL,
  `cate_nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`cate_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE INDEX `fk_entrada_categoria_entrada_tipo1_idx` ON `punored`.`entrada_categoria` (`cate_tipo_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`entrada_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`entrada_tipo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`entrada_tipo` (
  `tipo_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`tipo_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`incidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`incidencia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`incidencia` (
  `inci_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inci_titulo` VARCHAR(45) NULL DEFAULT NULL,
  `inci_descripcion` TEXT NULL DEFAULT NULL,
  `inci_foto` VARCHAR(45) NULL DEFAULT NULL,
  `inci_latitude` VARCHAR(45) NULL DEFAULT NULL,
  `inci_longitude` VARCHAR(45) NULL DEFAULT NULL,
  `inci_pmas` INT(11) NULL DEFAULT NULL,
  `inci_pmenos` INT(11) NULL DEFAULT NULL,
  `inci_espublico` BIT(1) NULL DEFAULT NULL,
  `inci_cate_id` INT(11) NULL DEFAULT NULL,
  `inci_usua_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`inci_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_incidencia_usuario1_idx` ON `punored`.`incidencia` (`inci_usua_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_incidencia_incidencia_tegoria1_idx` ON `punored`.`incidencia` (`inci_cate_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`incidencia_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`incidencia_categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`incidencia_categoria` (
  `cate_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cate_nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cate_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`usuario` (
  `usua_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usua_nombres` VARCHAR(45) NULL DEFAULT NULL,
  `usua_movil` VARCHAR(45) NULL DEFAULT NULL,
  `usua_email` VARCHAR(45) NULL DEFAULT NULL,
  `usua_password` VARCHAR(45) NULL DEFAULT NULL,
  `usua_foto` VARCHAR(45) NULL DEFAULT NULL,
  `usua_descripcion` TEXT NULL DEFAULT NULL,
  `usua_password2` VARCHAR(45) NULL DEFAULT NULL,
  `usua_activo` BIT(1) NOT NULL DEFAULT b'1',
  `usua_tipo_id` INT(11) NULL DEFAULT NULL,
  `usua_lastip` VARCHAR(45) NULL DEFAULT NULL,
  `usua_nick` VARCHAR(45) NULL,
  `usua_apellidos` VARCHAR(45) NULL,
  PRIMARY KEY USING BTREE (`usua_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unico_mail_egresado` USING BTREE ON `punored`.`usuario` (`usua_email`);

SHOW WARNINGS;
CREATE INDEX `fk_usuario_usuario_tipo1_idx` USING BTREE ON `punored`.`usuario` (`usua_tipo_id`);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`usuario_encuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`usuario_encuesta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`usuario_encuesta` (
  `rela_id` INT(11) NOT NULL,
  `rela_usua_id` INT(11) NULL DEFAULT NULL,
  `rela_encu_id` INT(11) NULL DEFAULT NULL,
  `rela_fechareg` DATETIME NULL DEFAULT NULL,
  `rela_valora` BIT(1) NULL,
  `rela_deta_id` INT NULL,
  PRIMARY KEY (`rela_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_usuario_encuesta_encuesta1_idx` ON `punored`.`usuario_encuesta` (`rela_encu_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_usuario_encuesta_usuario1_idx` ON `punored`.`usuario_encuesta` (`rela_usua_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`usuario_entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`usuario_entrada` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`usuario_entrada` (
  `rela_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rela_usua_id` INT(11) NULL,
  `rela_entr_id` INT(11) NULL,
  `rela_nmas` INT(11) NOT NULL DEFAULT '0',
  `rela_nmenos` INT(11) NOT NULL DEFAULT '0',
  `rela_like` BIT(1) NOT NULL DEFAULT b'0',
  `rela_fechareg` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`rela_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE INDEX `fk_usuario_entrada_entrada1_idx` USING BTREE ON `punored`.`usuario_entrada` (`rela_entr_id`);

SHOW WARNINGS;
CREATE INDEX `fk_usuario_entrada_usuario1_idx` USING BTREE ON `punored`.`usuario_entrada` (`rela_usua_id`);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`usuario_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`usuario_tipo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`usuario_tipo` (
  `tipo_id` INT(11) NOT NULL,
  `tipo_nombre` VARCHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`tipo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
