-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 11:26:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema punored
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `punored` ;

-- -----------------------------------------------------
-- Schema punored
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `punored` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `punored` ;

-- -----------------------------------------------------
-- Table `punored`.`entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`entrada` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`entrada` (
  `entr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `entr_usua_id` INT(11) NULL DEFAULT NULL,
  `entr_titulo` VARCHAR(150) NULL DEFAULT NULL,
  `entr_descripcion` TEXT NULL DEFAULT NULL,
  `entr_foto` VARCHAR(45) NULL DEFAULT NULL,
  `entr_url` VARCHAR(150) NULL DEFAULT NULL,
  `entr_area_id` INT(11) NULL DEFAULT NULL,
  `entr_fechareg` DATETIME NULL DEFAULT NULL,
  `entr_fechapub` DATETIME NULL DEFAULT NULL,
  `entr_espublico` BIT(1) NOT NULL DEFAULT b'1',
  `entr_pmas` INT(11) NOT NULL DEFAULT '0',
  `entr_pmenos` INT(11) NOT NULL DEFAULT '0',
  `entr_cate_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`entr_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE INDEX `fk_empleo_usuario1_idx` USING BTREE ON `punored`.`entrada` (`entr_usua_id`) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_entrada_habilidad_area1_idx` USING BTREE ON `punored`.`entrada` (`entr_area_id`) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_entrada_entrada_categoria1_idx` USING BTREE ON `punored`.`entrada` (`entr_cate_id`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`entrada_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`entrada_categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`entrada_categoria` (
  `cate_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cate_nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`cate_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`usuario` (
  `usua_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usua_nombres` VARCHAR(45) NULL DEFAULT NULL,
  `usua_apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `usua_movil` VARCHAR(45) NULL DEFAULT NULL,
  `usua_email` VARCHAR(45) NULL DEFAULT NULL,
  `usua_password` VARCHAR(45) NULL DEFAULT NULL,
  `usua_foto` VARCHAR(45) NULL DEFAULT NULL,
  `usua_descripcion` TEXT NULL DEFAULT NULL,
  `usua_lastip` VARCHAR(45) NULL DEFAULT NULL,
  `usua_tipo_id` INT(11) NULL DEFAULT NULL,
  `usua_password2` VARCHAR(45) NULL DEFAULT NULL,
  `usua_activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY USING BTREE (`usua_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unico_mail_egresado` USING BTREE ON `punored`.`usuario` (`usua_email`) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_usuario_usuario_tipo1_idx` USING BTREE ON `punored`.`usuario` (`usua_tipo_id`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`usuario_entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`usuario_entrada` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`usuario_entrada` (
  `rela_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rela_usua_id` INT(11) NULL DEFAULT NULL,
  `rela_entr_id` INT(11) NULL DEFAULT NULL,
  `rela_nmas` INT(11) NOT NULL DEFAULT '0',
  `rela_nmenos` INT(11) NOT NULL DEFAULT '0',
  `rela_like` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY USING BTREE (`rela_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE INDEX `fk_usuario_entrada_entrada1_idx` USING BTREE ON `punored`.`usuario_entrada` (`rela_entr_id`) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_usuario_entrada_usuario1_idx` USING BTREE ON `punored`.`usuario_entrada` (`rela_usua_id`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `punored`.`usuario_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `punored`.`usuario_tipo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `punored`.`usuario_tipo` (
  `tipo_id` INT(11) NOT NULL,
  `tipo_nombre` VARCHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`tipo_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
